<?php
$doctors = [
    'dr-lata-goyal' => [
        'name' => 'Dr. Lata Goyal',
        'specialty' => 'Obstetrics & Gynaecology',
        'degrees' => 'MBBS, MS (Obstetrics & Gynaecology) | Senior Consultant & IVF Specialist',
        'experience' => '15+ Years',
        'img' => 'lata-goyal.jpg',
        'bio' => 'Dr. Lata Goyal is a renowned Gynecologist and Infertility Specialist based in Ambikapur. With over 15 years of experience, she has pioneered assisted reproductive technologies (ART) in the Surguja district. She is known for her compassionate care and high success rates in IVF and normal deliveries.',
        'long_bio' => 'Dr. Lata Goyal has been serving the community of Chhattisgarh for over a decade. Her commitment to bringing advanced medical technology to rural areas led to the establishment of the first IVF center in Ambikapur. She is a member of several prestigious medical associations and regularly participates in national health conferences.',
        'expertise' => [
            'High-risk Pregnancy',
            'IVF & Infertility',
            'Laparoscopic Gynaec Surgery',
            'PCOS Management',
            'Prenatal Care',
        ],
        'filters' => ['gynecology']
    ],
    'dr-tanay-goyal' => [
        'name' => 'Dr. Tanay Goyal',
        'specialty' => 'Orthopaedics',
        'degrees' => 'MBBS, MS (Orthopaedics) | Senior Orthopedic Surgeon',
        'experience' => '10+ Years',
        'img' => 'tanay-goyal.jpg',
        'bio' => 'Dr. Tanay Goyal is a highly skilled Orthopedic Surgeon at Sankalp Hospital. He is an expert in joint replacement and sports injuries, having performed hundreds of successful knee and hip surgeries. He is dedicated to restoring mobility for his patients in the Surguja region.',
        'long_bio' => 'Dr. Tanay is known for his precision in surgery and his dedicated post-operative care. He specializes in advanced procedures like knee and hip replacement, helping senior citizens regain their independence. He also provides emergency trauma care for accident victims 24/7 at Sankalp Hospital.',
        'expertise' => [
            'Joint Replacement',
            'ACL & Sports Injury',
            'Fracture Management',
            'Spine Surgery',
            'Arthroscopy',
        ],
        'filters' => ['orthopedics']
    ],
    'dr-suneedh-gupta' => [
        'name' => 'Dr. Suneedh Gupta',
        'specialty' => 'Oral & Maxillofacial Surgery',
        'degrees' => 'BDS, MDS (Oral & Maxillofacial Surgery) | Consultant Oral & Maxillofacial Surgeon',
        'experience' => '10+ Years',
        'img' => 'suneedh-gupta.jpg',
        'bio' => 'Dr. Suneedh Gupta is a highly skilled Oral & Maxillofacial Surgeon at Sankalp Hospital. He specializes in surgeries of the face, mouth, and jaws, including facial trauma management, oral pathology, and complex tooth extractions. He is dedicated to restoring facial function and aesthetics for his patients.',
        'long_bio' => 'Dr. Suneedh is known for his surgical precision in treating facial fractures and performing complex jaw surgeries. He works closely with other specialists at Sankalp Hospital to provide comprehensive care for trauma victims and patients with oral diseases.',
        'expertise' => [
            'Facial Trauma Surgery',
            'Jaw Realignment',
            'Oral Cancer Screening',
            'Complex Extractions',
            'Dental Implants',
        ],
        'filters' => ['dentistry', 'surgery']
    ],
    'dr-himanshu-gupta' => [
        'name' => 'Dr. Himanshu Gupta',
        'specialty' => 'Oncology',
        'degrees' => 'MBBS, MD / DNB - Medical Oncology',
        'experience' => '10+ Years',
        'img' => 'himanshu-gupta.jpg',
        'bio' => 'Cancer & Chemotherapy Specialist coordinating tumor chemotherapies and cancer screening packages.',
        'long_bio' => 'Dr. Himanshu Gupta is the Oncology and Cancer Care Specialist at Sankalp Hospital. He manages chemotherapy protocols, coordinates multi-specialty cancer treatments, and leads cancer screening packages. He is committed to providing empathetic, patient-centered care and advanced cancer therapy.',
        'expertise' => [
            'Chemotherapy Administration',
            'Targeted Immunotherapy',
            'Cancer Screening & Diagnosis',
            'Tumor Triage',
            'Palliative & Supportive Care',
        ],
        'filters' => ['oncology']
    ],
    'dr-chandra-mukesh-dhawde' => [
        'name' => 'Dr. Chandra Mukesh Dhawde',
        'specialty' => 'General & Laparoscopic Surgery',
        'degrees' => 'MBBS, MS - Laparoscopic Surgeon',
        'experience' => '12+ Years',
        'img' => 'chandra-dhawde.jpg',
        'bio' => 'Expert in laparoscopic keyhole surgery, hernia treatment, and general abdominal surgeries.',
        'long_bio' => 'Dr. Chandra Mukesh Dhawde is an expert Laparoscopic and General Surgeon at Sankalp Hospital. He specializes in minimally invasive keyhole procedures, abdominal wall reconstructions, and hernia repairs. He focuses on modern surgical methods that reduce post-operative recovery times and pain.',
        'expertise' => [
            'Laparoscopic Keyhole Surgery',
            'Hernia Reconstructions',
            'Appendectomy & Cholecystectomy',
            'Abdominal Trauma Care',
            'Thyroid & Breast Surgeries',
        ],
        'filters' => ['surgery']
    ],
    'dr-sanjay-goyal' => [
        'name' => 'Dr. Sanjay Goyal',
        'specialty' => 'Ophthalmology (Senior Specialist)',
        'degrees' => 'MBBS, MS (Ophthalmology) | Founder & Senior Eye Surgeon',
        'experience' => '25+ Years',
        'img' => 'sanjay-goyal.jpg',
        'bio' => 'Dr. Sanjay Goyal is the founder of Sankalp Hospital and a pioneer of modern ophthalmology in the Surguja region. With over 25 years of experience, he has performed thousands of successful eye surgeries and is dedicated to providing world-class vision care to the community.',
        'long_bio' => 'Dr. Sanjay\'s vision for Sankalp Hospital was to provide world-class healthcare facilities to the people of Ambikapur at affordable costs. His expertise in complex ocular trauma and advanced cataract surgery makes him the most sought-after ophthalmologist in the region.',
        'expertise' => [
            'Micro-Incision Cataract Surgery',
            'Laser Eye Treatment',
            'Ocular Trauma',
            'Corneal Diseases',
            'Comprehensive Eye Care',
        ],
        'filters' => ['ophthalmology']
    ],
    'dr-manoj-bharti' => [
        'name' => 'Dr. Manoj Bharti',
        'specialty' => 'Dentistry',
        'degrees' => 'BDS - Consultant Dentist',
        'experience' => '10+ Years',
        'img' => 'manoj-bharti.jpg',
        'bio' => 'Experienced Dentist providing comprehensive dental care, root canals, and cosmetic dental treatments.',
        'long_bio' => 'Dr. Manoj Bharti is an experienced Consultant Dentist at Sankalp Hospital. He provides a wide range of dental care services, from preventative dental checks and restorative fillings to root canals, crowns, bridges, and cosmetic smile designs, ensuring beautiful and healthy smiles.',
        'expertise' => [
            'Root Canal Treatment (RCT)',
            'Dental Crowns & Bridges',
            'Cosmetic Dentistry',
            'Teeth Scaling & Whitening',
            'Preventative Dental Care',
        ],
        'filters' => ['dentistry', 'surgery']
    ],
    'dr-nilesh-goyal' => [
        'name' => 'Dr. Nilesh Goyal',
        'specialty' => 'General & Laparoscopic Surgery',
        'degrees' => 'MBBS, MS (General Surgery) | Consultant General & Laparoscopic Surgeon',
        'experience' => '10+ Years',
        'img' => 'nilesh-goyal.jpg',
        'bio' => 'Dr. Nilesh Goyal is an expert General and Laparoscopic Surgeon at Sankalp Hospital. He specializes in minimally invasive surgeries, helping patients recover faster with less pain. He has extensive experience in performing complex abdominal surgeries and trauma management.',
        'long_bio' => 'Dr. Nilesh is committed to providing high-quality surgical treatment with a focus on patient safety and comfort. His expertise in laparoscopic surgery ensures smaller incisions, less post-operative pain, and a quicker return to daily activities for his patients.',
        'expertise' => [
            'Laparoscopic Gallbladder Surgery',
            'Hernia Repair',
            'Appendectomy',
            'Abdominal Surgery',
            'Trauma Surgery',
        ],
        'filters' => ['surgery']
    ],
    'dr-vijaya-singh' => [
        'name' => 'Dr. Vijaya Singh',
        'specialty' => 'Obstetrics & Gynaecology',
        'degrees' => 'MBBS, DGO - Gynecology',
        'experience' => '10+ Years',
        'img' => 'vijaya-singh.jpg',
        'bio' => 'Dedicated Gynecologist offering general maternity checkups, out-patient screenings, and normal deliveries.',
        'long_bio' => 'Dr. Vijaya Singh is a dedicated Gynecologist at Sankalp Hospital offering comprehensive outpatient care, routine prenatal screenings, and normal deliveries. She is known for her approachable nature and focus on health education for young mothers.',
        'expertise' => [
            'Antenatal & Postnatal Care',
            'Routine Gynaec Screenings',
            'Normal Delivery Management',
            'Family Planning Guidance',
            'Menopause Counselling',
        ],
        'filters' => ['gynecology']
    ],
    'dr-ankit-sharma' => [
        'name' => 'Dr. Ankit Sharma',
        'specialty' => 'Psychiatry',
        'degrees' => 'MBBS, MD (Psychiatry) | Consultant Psychiatrist',
        'experience' => '8+ Years',
        'img' => 'ankit-sharma.jpg',
        'bio' => 'Dr. Ankit Sharma is a compassionate Psychiatrist at Sankalp Hospital, dedicated to providing comprehensive mental health care. He specializes in treating a wide range of psychological conditions and is committed to helping his patients achieve mental well-being and resilience.',
        'long_bio' => 'Dr. Ankit believes in a holistic approach to mental health, combining medication management with evidence-based psychotherapy. He treats conditions like anxiety disorders, depression, bipolar disorder, and addiction with the utmost confidentiality and professionalism.',
        'expertise' => [
            'Depression & Anxiety',
            'Stress Management',
            'De-addiction',
            'Child & Adolescent Psychiatry',
            'Counseling',
        ],
        'filters' => ['psychiatry']
    ],
    'dr-ankita-bansal-goyal' => [
        'name' => 'Dr. Ankita Bansal Goyal',
        'specialty' => 'Obstetrics & Gynaecology',
        'degrees' => 'MD (Obstetrics & Gynaecology) - PGIMER CHD, FMAS | Consultant Laparoscopic Surgeon & Gynaecologist',
        'experience' => '8+ Years',
        'img' => 'ankita-goyal.jpg',
        'bio' => 'Dr. Ankita Bansal Goyal is a gold-medalist from PGIMER Chandigarh and a pioneer in 3D Laparoscopic Surgery in Ambikapur. She specializes in minimally invasive gynecological procedures, including laparoscopic hysterectomy and myomectomy, providing advanced surgical care for women.',
        'long_bio' => 'Dr. Ankita\'s training at PGIMER Chandigarh and her fellowship in minimal access surgery allow her to perform complex surgeries with minimal scarring and faster recovery. She is dedicated to improving women\'s quality of life through advanced medical and surgical interventions for conditions like endometriosis, uterine fibroids, and heavy menstrual bleeding.',
        'expertise' => [
            '3D Laparoscopic Surgery',
            'Laparoscopic Hysterectomy',
            'PCOS Specialist',
            'High-risk Pregnancy',
            'Infertility Care',
        ],
        'filters' => ['gynecology', 'surgery']
    ],
    'dr-yuvan-prasannaa' => [
        'name' => 'Dr. Yuvan Prasannaa',
        'specialty' => 'Pediatrics',
        'degrees' => 'MBBS, MD - Pediatrics',
        'experience' => '8+ Years',
        'img' => 'yuvan.jpg',
        'bio' => 'Consultant Pediatrician providing general pediatric consultations and child growth tracking.',
        'long_bio' => 'Dr. Yuvan Prasannaa is a Consultant Pediatrician at Sankalp Hospital. He offers routine child healthcare, growth and development tracking, childhood immunizations, and guidance on nutritional needs for infants and young children in the region.',
        'expertise' => [
            'Child Growth Monitoring',
            'Immunization & Vaccination',
            'Childhood Infections Care',
            'Pediatric Nutrition Counseling',
            'Asthma & Allergy Management',
        ],
        'filters' => ['pediatrics']
    ],
    'dr-nagaraj-g-naik' => [
        'name' => 'Dr. Nagaraj G Naik',
        'specialty' => 'Anesthesiology',
        'degrees' => 'DA, DNB - Anaesthesiology',
        'experience' => '15+ Years',
        'img' => 'nagaraj-naik.jpg',
        'bio' => 'Consultant Anaesthetist and Intensivist coordinating surgical sedation and painless labor protocols.',
        'long_bio' => 'Dr. Nagaraj G Naik is a Consultant Anaesthetist and Intensivist at Sankalp Hospital with 15+ years of clinical experience. He coordinates surgical sedation, critical care management in the ICU, and manages advanced labor analgesia (painless labor) protocols.',
        'expertise' => [
            'General & Regional Anesthesia',
            'Painless Labor (Epidural)',
            'ICU Life Support Coordination',
            'Pre-Anesthetic Health Profiling',
            'Post-Operative Pain Relief',
        ],
        'filters' => ['anesthesia']
    ],
    'dr-shailesh-gupta' => [
        'name' => 'Dr. Shailesh Gupta',
        'specialty' => 'Cardiology & Internal Medicine',
        'degrees' => 'MBBS, MD (Medicine) | Senior Physician & Heart Specialist',
        'experience' => '15+ Years',
        'img' => 'shailesh-gupta.jpg',
        'bio' => 'Dr. Shailesh Gupta is a highly experienced Physician and Cardiologist at Sankalp Hospital. With over 15 years of clinical practice, he specializes in managing complex medical conditions, particularly heart disease, hypertension, and metabolic disorders like diabetes.',
        'long_bio' => 'Dr. Shailesh provides comprehensive care for heart patients, including management of stable angina, heart failure, and complex arrhythmias. He also manages chronic lifestyle diseases like hypertension and diabetes, ensuring his patients live long and healthy lives.',
        'expertise' => [
            'Heart Disease',
            'Hypertension',
            'Diabetes Management',
            'General Medicine',
            'Preventive Cardiology',
        ],
        'filters' => ['medicine']
    ],
    'dr-usha-armo' => [
        'name' => 'Dr. Usha Armo',
        'specialty' => 'ENT (Otolaryngology)',
        'degrees' => 'MBBS, MS (ENT) | Senior ENT Consultant',
        'experience' => '12+ Years',
        'img' => 'usha-armo.jpg',
        'bio' => 'Dr. Usha Armo is a dedicated ENT Specialist at Sankalp Hospital with over 12 years of clinical experience. She is highly proficient in managing both medical and surgical conditions of the ear, nose, and throat. Her expertise in endoscopy and microsurgery has helped many patients find relief from chronic ENT problems.',
        'long_bio' => 'Dr. Usha is known for her accurate diagnosis and personalized treatment plans. She utilizes advanced diagnostic tools like video endoscopy to provide the best care for chronic sinusitis, hearing impairment, and throat disorders. Her patient-friendly approach makes her the most trusted ENT specialist in the Surguja region.',
        'expertise' => [
            'Sinusitis Treatment',
            'Tympanoplasty',
            'Hearing Loss',
            'Tonsillectomy',
            'Nasal Endoscopy',
        ],
        'filters' => ['ent']
    ],
    'dr-sukirti-chauhan' => [
        'name' => 'Dr. Sukirti Chauhan',
        'specialty' => 'Obstetrics & Gynaecology',
        'degrees' => 'MBBS, MS - Obs & Gynaecology',
        'experience' => '10+ Years',
        'img' => 'sukirti-chauhan.jpg',
        'bio' => 'Specialist Gynecologist expert in maternal health screenings, prenatal checks, and deliveries.',
        'long_bio' => 'Dr. Sukirti Chauhan is a Specialist Gynecologist at Sankalp Hospital. She focuses on outpatient consultations, preventative maternal health screenings, prenatal checks, family planning, and handling both normal and assisted deliveries with extreme care.',
        'expertise' => [
            'Prenatal Diagnostics',
            'Maternal Screening Panels',
            'Normal Deliveries',
            'Outpatient Gynaecology',
            'Adolescent Gynae Counselling',
        ],
        'filters' => ['gynecology']
    ],
    'dr-megha-goyal' => [
        'name' => 'Dr. Megha Goyal',
        'specialty' => 'Neonatology & Pediatrics',
        'degrees' => 'MBBS, MD (Pediatrics) | Consultant Neonatologist',
        'experience' => '7+ Years',
        'img' => 'megha-goyal.jpg',
        'bio' => 'Dr. Megha Goyal is a dedicated Neonatologist at Sankalp Hospital, specializing in the care of newborns and premature infants. Her expertise in the Neonatal Intensive Care Unit (NICU) has saved many lives, providing the highest standard of care for the most vulnerable patients.',
        'long_bio' => 'Dr. Megha\'s dedication to neonatal health ensures that every baby born at Sankalp Hospital has immediate access to expert care if complications arise. She also provides regular pediatric consultations, guiding parents through the crucial early years of their child\'s development.',
        'expertise' => [
            'Newborn Care',
            'NICU Specialist',
            'Premature Baby Care',
            'Pediatric Emergencies',
            'Childhood Immunization',
        ],
        'filters' => ['pediatrics']
    ],
    'dr-akshaya-goyal' => [
        'name' => 'Dr. Akshaya Goyal',
        'specialty' => 'Ophthalmology (Eye Care)',
        'degrees' => 'MBBS, MS (Ophthalmology) | Consultant Ophthalmologist',
        'experience' => '7+ Years',
        'img' => 'akshaya-goyal.jpg',
        'bio' => 'Dr. Akshaya Goyal is a skilled Eye Specialist at Sankalp Hospital, dedicated to providing advanced eye care services. He specializes in modern cataract surgery and managing complex eye conditions, ensuring clear vision for his patients in Ambikapur.',
        'long_bio' => 'Dr. Akshaya is committed to preventing blindness and restoring vision. He utilizes the latest Phacoemulsification technology for cataract surgery, allowing for stitch-less and painless recovery. He also specializes in managing glaucoma and diabetic retinopathy to protect your long-term eye health.',
        'expertise' => [
            'Phaco Cataract Surgery',
            'Glaucoma Management',
            'Diabetic Retinopathy',
            'Refractive Errors',
            'Eye Trauma',
        ],
        'filters' => ['ophthalmology']
    ],
    'dr-akshay-gupta' => [
        'name' => 'Dr. Akshay Gupta',
        'specialty' => 'Rheumatology & Internal Medicine',
        'degrees' => 'MD (Medicine) | Consultant Physician & Rheumatologist',
        'experience' => '5+ Years',
        'img' => 'akshay-gupta.jpg',
        'bio' => 'Dr. Akshay Gupta is a Consultant Physician and Rheumatologist with expertise in Internal Medicine, autoimmune diseases, arthritis, and complex medical disorders. He completed his MBBS from Vardhman Mahavir Medical College & Safdarjung Hospital and MD (Medicine) from Dr. Ram Manohar Lohia Hospital, New Delhi. He is recognized as the first and only rheumatology specialist serving the Surguja region.',
        'long_bio' => 'Dr. Akshay Gupta is a Consultant Physician and Rheumatologist at Sankalp Hospital. He completed his MBBS from Vardhman Mahavir Medical College & Safdarjung Hospital and MD from RML Hospital, New Delhi. He is recognized as the first and only rheumatology specialist serving the Surguja region.',
        'expertise' => [
            'Rheumatology',
            'Rheumatoid Arthritis',
            'Ankylosing Spondylitis',
            'Lupus (SLE)',
            'Psoriatic Arthritis',
            'Gout',
            'Vasculitis',
            'Osteoporosis',
            'Diabetes & Hypertension',
            'General Internal Medicine',
        ],
        'filters' => ['medicine']
    ],
    'dr-ankit-gupta' => [
        'name' => 'Dr. Ankit Gupta',
        'specialty' => 'Pediatrics',
        'degrees' => 'MBBS, DCH | Senior Consultant Pediatrician',
        'experience' => '10+ Years',
        'img' => 'ankit-gupta.jpg',
        'bio' => 'Dr. Ankit Gupta is a highly regarded Pediatrician in Ambikapur, known for his excellence in child healthcare. He provides comprehensive care for infants, children, and adolescents, specializing in growth monitoring, nutrition, and infectious diseases.',
        'long_bio' => 'From routine checkups to managing complex childhood illnesses, Dr. Ankit\'s expertise ensures that your child\'s health is in safe hands. He is a strong advocate for vaccination and preventive healthcare, helping parents raise healthy and happy children.',
        'expertise' => [
            'Child Vaccination',
            'Neonatal Care',
            'Pediatric Nutrition',
            'Child Growth Monitoring',
            'Infectious Diseases',
        ],
        'filters' => ['pediatrics']
    ],
    'dr-rimsha-lakesh-sahu' => [
        'name' => 'Dr. Rimsha Lakesh Sahu',
        'specialty' => 'Nutrition & Dietetics',
        'degrees' => 'M.Sc. (Nutrition & Dietetics) | Consultant Nutritionist',
        'experience' => '5+ Years',
        'img' => 'rimsha-sahu.jpg',
        'bio' => 'Dr. Rimsha Lakesh Sahu is a highly skilled Nutritionist at Sankalp Hospital, helping patients achieve their health goals through personalized diet plans. She specializes in clinical nutrition, helping patients manage chronic diseases like diabetes and hypertension through lifestyle modifications.',
        'long_bio' => 'Dr. Rimsha believes that nutrition is the foundation of good health. She works closely with patients to create sustainable eating habits that promote healing and long-term wellness. Whether you\'re looking to lose weight or manage a clinical condition, her personalized approach will help you achieve your goals.',
        'expertise' => [
            'Weight Loss Plans',
            'Diabetic Diet',
            'Therapeutic Nutrition',
            'Child Nutrition',
            'Lifestyle Coaching',
        ],
        'filters' => ['nutrition']
    ]
];
